### ISSUE TITLE
Credentials list in docker doesn't work

### ISSUE THREAD

**Issue by Fantomatic** [jenkinsci/docker-plugin#250]
I'm trying to use this plugin, and i have encounter a bug.
The list where there should be all my credentials in Jenkins isn't working. 
I'm using now the last version of jenkins and everything is update.
It's a blocking problem, because it  doesn't allow me to connect distant vm to the master jenkins.

**Comment by KostyaSha** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue#Howtoreportanissue-WhatinformationtoprovideforEnvironmentandDescription

**Comment by KostyaSha** [comment]
Please check that ssh-credentials-plugin and credentials-plugin is not missing in your installation.

**Comment by svnlto** [comment]
I've got the same issue.

**Comment by KostyaSha** [comment]
@svnlto please provide some logs/description/steps for reproducing https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md

**Comment by pcas** [comment]
I thought I was having this same issue when I upgraded from 0.8.0 to 0.10.1, but it looks like there are now two credentials boxes. 

The main "Docker" settings that seems to be stuck at "- none -" and attempting to add more creds to the list does nothing. 

One under "Docker Template" per image which has all of the credentials available. This allows me connect as before.

Jenkins ver. 1.619
Credentials plugin: 1.22
SSH-Credentials plugin: 1.11
This plugin: 0.10.1

**Comment by KostyaSha** [comment]
@pcas your issue unrelated and fixed in 0.10.2

**Comment by rdaviscc** [comment]
Hello I am still having this issue with a new jenkins installation.  
Docker plugin 0.10.2
ssh credentials plugin 1.11
Credentials Plug 1.22
Jenkins Version 1.622

Running on Mac Yosemite and Java 1.8

**Comment by rdaviscc** [comment]
I should also mention that everything was a fresh install.

**Comment by KostyaSha** [comment]
@rdaviscc please open new issue and provide some screenshots

**Comment by rdaviscc** [comment]
Done and Done https://github.com/jenkinsci/docker-plugin/issues/290

**Comment by KostyaSha** [comment]
@Fantomatic @pcas @svnlto please provide screenshots

**Comment by Fantomatic** [comment]
![screenshot from 2015-07-31 16 01 14](https://cloud.githubusercontent.com/assets/6103180/9008916/bf3a24a8-379d-11e5-96f8-461bb47411f1.png)

And so i have a lot of credentials ( sorry for not responding, we found another solution, a little less integrated but well, who work for now ) which doesn't appear in THIS combobox. 
Oh and when i add a credential with the button just on the right of the failed combobox, it add the credential. Just still don't appear in it.

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/docker-plugin/issues/290#issuecomment-125784961
