### ISSUE TITLE
1.1.1 Docker containers are spawend too late

### ISSUE THREAD

**Issue by soczkers** [jenkinsci/docker-plugin#579]
- [1.1.1] docker-plugin version you use
 - [ 2.98.1] jenkins version you use
 - [ 17.05.0-ce] docker engine version you use
 
When new slave/docker container is spawned I see:
`Dec 13, 2017 5:16:38 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: label_name
Dec 13, 2017 5:16:38 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'image_name', for label: 'label_name', in cloud: 'cloud_name'
Dec 13, 2017 5:16:38 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave`

And as results I see successfully provisioned slave.
But sometimes I see some new jobs waiting in queue, which should be executed on labels releated with dockers, but new slaves are not provisioned. Jobs waiting in that shape even about 10minutes. I dont see in logs(at this time) any new entrys from 
`com.nirima.jenkins.plugins.docker`

Edit: I enabled some more logs and i see:
`Dec 13, 2017 6:08:16 PM FINEST io.jenkins.docker.FastNodeProvisionerStrategy applyFoCloud
Available executors=0, connecting=0, planned=10
Dec 13, 2017 6:08:16 PM FINE io.jenkins.docker.FastNodeProvisionerStrategy applyFoCloud
Available capacity=10, currentDemand=7
Dec 13, 2017 6:08:16 PM FINE io.jenkins.docker.FastNodeProvisionerStrategy applyFoCloud
Provisioning completed`

My question is why planned value is so high and what does it mean? Looks like capacity is sum of (executors, connecting and planned) and new slaves are spawned only when capacity< currentDemand

**Comment by ndeloof** [comment]
Those nodes all fail to connect, aren't they ?
Looks like this is same issue as https://github.com/jenkinsci/docker-plugin/issues/568

**Comment by soczkers** [comment]
I think it isnt. I think problem is somewhere in labels.
Initially I had multiple labels related with these containers/templates. I
removed these labels and left only one. - doesn't help. But after jenkins
master restart - everything back to normal. Now containers are spawned
verry fast. Probably we hasn't that issue before 1.1 because we used some
other strategy where some slaves were waiting for next execution.

Look what I pasted :

Dec 13, 2017 6:08:16 PM FINEST
> io.jenkins.docker.FastNodeProvisionerStrategy applyFoCloud Available
> executors=0, connecting=0, planned=10



> Dec 13, 2017 6:08:16 PM FINE io.jenkins.docker.FastNodeProvisionerStrategy
> applyFoCloud Available capacity=10, currentDemand=7



> Dec 13, 2017 6:08:16 PM FINE io.jenkins.docker.FastNodeProvisionerStrategy
> applyFoCloud Provisioning completed


 Based on that knowladge and that lines:

https://github.com/jenkinsci/docker-plugin/blob/8de03a4cc0381adb7c7a19eddedc400715dff936/src/main/java/io/jenkins/docker/FastNodeProvisionerStrategy.java#L71

there is no way to even try to spawn new connection. Right?

2017-12-15 0:27 GMT+01:00 Nicolas De loof <notifications@github.com>:

**Comment by ndeloof** [comment]
should be fixed by https://github.com/jenkinsci/docker-plugin/commit/b906c37f0add6a4a44fb4858aa8ff9de0ebeeabe#diff-0a438d5fa3c18711a9f82de9b72440c0R277

**Comment by sporkisfaster** [comment]
Still having this issue. Getting Jenkins doesn't have label testslave in any job configuration in jenkins. Tried pipeline, freestyle, etc. Tried SSH injection, manually pasting the key, JNLP, etc. Made sure there were no leading spaces in the label name. Not sure what's going on.

Jenkins: v 2.100
Docker plugin 1.1.2
Version = 17.07.0-ce, API Version = 1.31

**Comment by csakaszamok** [comment]
+1

**Comment by wkonsek** [comment]
+1 
Jenkins 2.89.3
Docker plugin 1.1.2
Docker version 18.01.0-ce

**Comment by jungopro** [comment]
+1

**Comment by aquasika** [comment]
+1

**Comment by jjo** [comment]
+1 having this issue
Jenkins 2.89.3
Docker plugin 1.1.2
Docker version 1.13.1

**Comment by missedone** [comment]
+ issue remains on:
Jenkins 2.107.3
Docker Plugin 1.1.4
Docker Version: 17.12.01

@ndeloof , looks like your commit b906c37#diff-0a438d5fa3c18711a9f82de9b72440c0R277 is not relate to this issue.

**Comment by missedone** [comment]
@ndeloof , in Jenkins system configure, in Docker template settings, i noticed that there's warning besides the "Enabled" button, said it's disabled due to error in my slave docker image, so looks like somehow it was auto disabled.

after waiting for couple of minutes, i back work again.

**Comment by pjdarton** [comment]
@missedone FYI the provisioning failure mentioned there is also logged in the logs.
...and the next release has better help text for this feature, plus the ability to configure how long Jenkins remembers these errors for.
